version: 0.2
phases:
  install:
    commands:
      - bash build_lambda.sh
#      - aws s3 sync $lambda_output_file s3://rbods-clamav/build/
  artifacts:
    type:
      - s3
    name:
      - rbods-clamav/build
    files:
      - lambda.zip
  #     - set -e
  #
  #     - yum update -y
  #     - yum install -y cpio python27-pip zip
  #     - pip install --no-cache-dir virtualenv
  #     - virtualenv env
  #     - . env/bin/activate
  #     - pip install --no-cache-dir -r requirements.txt
  #
  # pre_build:
  #   commands:
  #     - pushd /tmp
  #     - yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update
  #     - rpm2cpio clamav-0*.rpm | cpio -idmv
  #     - rpm2cpio clamav-lib*.rpm | cpio -idmv
  #     - rpm2cpio clamav-update*.rpm | cpio -idmv
  #     - popd
  #     - mkdir -p bin
  #     - cp /tmp/usr/bin/clamscan /tmp/usr/bin/freshclam /tmp/usr/lib64/* bin/.
  #     - echo "DatabaseMirror database.clamav.net" > bin/freshclam.conf
  # build:
  #   commands:
  #     - mkdir -p build
  #     - zip -r9 $lambda_output_file *.py bin
  #     - cd env/lib/python2.7/site-packages
  #     - zip -r9 $lambda_output_file *
